GET http://localhost:8080/opps

POST http://localhost:8080/opps
Content-Type: application/json

{
    "name": "Task",
    "desc": "asdfs fdsa",
    "lat": -122.0,
    "lon": 37.1,
    "start": 1664607148,
    "end": 1664607158
}

PUT http://localhost:8080/opps/13
Content-Type: application/json

{
    "name": "Updated Task",
    "desc": "asdfs fdsa",
    "lat": -122.0,
    "lon": 37.1,
    "start": 1664607148,
    "end": 1664607158
}

DELETE http://localhost:8080/opps/7

###

GET http://localhost:8080/users

GET http://localhost:8080/users/asdf

POST http://localhost:8080/users
Content-Type: application/json

{
  "id": "asdfsda"
}

PUT http://localhost:8080/users/asdfsda
Content-Type: application/json

{
  "id": "a"
}

DELETE http://localhost:8080/users/a
    "name": "technology"
}
