GET http://localhost:8080/items

POST http://localhost:8080/items
Content-Type: application/json

{
    "name": "Task",
    "desc": "asdfs fdsa"
}

PUT http://localhost:8080/items/7
Content-Type: application/json

{
    "name": "new",
    "desc": "also new"
}

DELETE http://localhost:8080/items/7

###

GET http://localhost:8080/users

GET http://localhost:8080/users/asdf

POST http://localhost:8080/users
Content-Type: application/json

{
  "id": "asdfsda"
}

PUT http://localhost:8080/users/asdfsda
Content-Type: application/json

{
  "id": "a"
}

DELETE http://localhost:8080/users/a

###

GET http://localhost:8080/tags

GET http://localhost:8080/tags/1

POST http://localhost:8080/tags
Content-Type: application/json


{
    "name": "technology"
}

PUT http://localhost:8080/tags/1
Content-Type: application/json

{
    "name": "tech"
}

DELETE http://localhost:8080/tags/1


