"""update opp schema

Revision ID: 3a73a2cf9e44
Revises: 8518f312bace
Create Date: 2022-10-07 20:07:19.718017

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3a73a2cf9e44"
down_revision = "8518f312bace"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("opps", sa.Column("isChurch", sa.Boolean(), nullable=False))
    op.add_column("opps", sa.Column("contact", sa.String(), nullable=True))
    op.add_column("opps", sa.Column("website", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("opps", "website")
    op.drop_column("opps", "contact")
    op.drop_column("opps", "isChurch")
    # ### end Alembic commands ###
