"""add user opp relationship

Revision ID: 4bf98fb50c5d
Revises: 
Create Date: 2022-10-11 21:32:48.727770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf98fb50c5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_opp_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('opp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opp_id'], ['opps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_opp_association')
    # ### end Alembic commands ###
