"""asdf

Revision ID: 629afa0f5fda
Revises: a78c5c515340
Create Date: 2022-10-15 03:00:49.312469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "629afa0f5fda"
down_revision = "a78c5c515340"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
