"""add rating to user opp relationship

Revision ID: 7dffb86a3fec
Revises: c84acf399fa7
Create Date: 2022-10-14 18:26:38.682223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dffb86a3fec'
down_revision = 'c84acf399fa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_opp_association', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_opp_association', 'rating')
    # ### end Alembic commands ###
