"""update opp schema

Revision ID: 93da53585063
Revises: 
Create Date: 2022-09-30 23:46:28.019913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93da53585063'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opps', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('opps', sa.Column('lon', sa.Float(), nullable=False))
    op.add_column('opps', sa.Column('start', sa.Integer(), nullable=False))
    op.add_column('opps', sa.Column('end', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opps', 'end')
    op.drop_column('opps', 'start')
    op.drop_column('opps', 'lon')
    op.drop_column('opps', 'lat')
    # ### end Alembic commands ###
