"""update lazy load perf

Revision ID: 9f67f328c062
Revises: f523cc094a99
Create Date: 2022-10-14 11:22:38.048228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f67f328c062'
down_revision = 'f523cc094a99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
