"""init

Revision ID: a78c5c515340
Revises: 
Create Date: 2022-10-15 02:59:24.431409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78c5c515340'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('isChurch', sa.Boolean(), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opp_id'), 'opp', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('children', sa.Boolean(), nullable=True),
    sa.Column('setup_labor', sa.Boolean(), nullable=True),
    sa.Column('audio_visual', sa.Boolean(), nullable=True),
    sa.Column('teaching', sa.Boolean(), nullable=True),
    sa.Column('food', sa.Boolean(), nullable=True),
    sa.Column('environment', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_opp_association',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('opp_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opp_id'], ['opp.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'opp_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_opp_association')
    op.drop_table('user')
    op.drop_index(op.f('ix_opp_id'), table_name='opp')
    op.drop_table('opp')
    # ### end Alembic commands ###
