"""change lazy load type

Revision ID: d6e4822ca24e
Revises: 88a25317af7c
Create Date: 2022-10-14 11:02:19.295622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e4822ca24e'
down_revision = '88a25317af7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
