"""update lazy loading recursion error

Revision ID: f523cc094a99
Revises: d6e4822ca24e
Create Date: 2022-10-14 11:12:56.198928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f523cc094a99'
down_revision = 'd6e4822ca24e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
