"""add tags table

Revision ID: 137dcb265736
Revises: cfe518face8c
Create Date: 2022-08-28 14:55:36.440681

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "137dcb265736"
down_revision = "cfe518face8c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
